### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by hellerve** [sdiehl/gevent-tutorial#49]
I translated the tutorial to german [here](https://hellerve.github.io/gevent-tutorial-de). 
The corresponding repo can be found [here](https://github.com/hellerve/gevent-tutorial-de).

**Comment by sdiehl** [comment]
Sweet, I added a note about the German version in fb3a722. Just host the translation on your Github and ping me if anything changes.

**Comment by hellerve** [comment]
Looks good. Thanks for all your work.
