### ISSUE TITLE
gevent.shutdown doesn't exist in gevent 1.0b2

### ISSUE THREAD

**Issue by aspidites** [sdiehl/gevent-tutorial#9]
The [Program Shutdown](http://sdiehl.github.com/gevent-tutorial/#program-shutdown) section suggests coupling gevent.event with gevent.shutdown to cause a program to exit immediately. gevent.shutdown doesn't exist in gevent 1.0b2, and it seems that this behavior is builtin autoamatically now (through the use of [gevent.hub.Hub.SYSTEM_ERROR](https://bitbucket.org/denis/gevent/src/91bea46584c9/gevent/hub.py#cl-283).

It would be nice if the tutorial mentioned this (or alternatively mentioned the tutorial was written for gevent 0.13.7 or earlier) as not to cause confusion when an AttributeError is raised.

**Comment by karlb** [comment]
This change is not live at http://sdiehl.github.io/gevent-tutorial/, yet.
